<?php
/**
 * @file
 * Main hooks for Islandora Badges.
 */

/**
 * Implements hook_menu().
 */
function islandora_badges_menu() {
  return array(
    'admin/islandora/tools/badges' => array(
      'title' => 'Islandora Badges Configuration',
      'description' => 'Configure Badges integration.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_badges_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_badges_block_info() {
  return array(
    'islandora_badges_altmetrics' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_NO_CACHE,
      'info' => t('Islandora Altmetrics'),
    ),
    'islandora_badges_scopus' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_NO_CACHE,
      'info' => t('Islandora Scopus'),  
    ),
    'islandora_badges_wos' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_NO_CACHE,
      'info' => t('Islandora Web of Science'),  
    ),    
  );
}

/**
 * Implements hook_block_view().
 */
 
function islandora_badges_block_view($delta) {
  $to_render = array();
  switch ($delta) {
   // Load the Altmetrics block
    case 'islandora_badges_altmetrics':
      $object = menu_get_object('islandora_object', 2);
      // Limit to citations with MODS DS. -- Eventually this should be removed, but without it you get warnings about getting properties of non-objects.
      if (!in_array('ir:citationCModel', $object->models) || !isset($object['MODS'])) {
        return;
      }
      // Get DOI.
      $doc = new DOMDocument();
      $doc->loadXML($object['MODS']->content);
      $xpath = new DOMXPath($doc);
      $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
      $xpath_results = $xpath->query(
        variable_get('islandora_badges_doi_xpath', '/mods:mods/mods:identifier[@type="doi"]')
      );
      $doi = $xpath_results->item(0)->nodeValue;
      if (!$doi) {
        return;
      }

      // Embed Altmetrics.
      $to_render['content']['altmetrics'] = array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('altmetric-embed'),
          'data-badge-type' => variable_get('islandora_badges_altmetrics_badge', 'Default'),
          'data-doi' => $doi,
          'data-badge-popover' => variable_get('islandora_badges_altmetrics_popover', 'right'),
          'data-hide-no-mentions' => 'true',
        ),
      );
      drupal_add_js('https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js', 'external');
      break;
 
  // Load the Scopus block
   case 'islandora_badges_scopus':
      $object = menu_get_object('islandora_object', 2);
      // Limit to citations with MODS DS -- see above.
      if (!in_array('ir:citationCModel', $object->models) || !isset($object['MODS'])) {
        return;
       }
      // Get DOI.
      $doc = new DOMDocument();
      $doc->loadXML($object['MODS']->content);
      $xpath = new DOMXPath($doc);
      $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
      $xpath_results = $xpath->query(
        variable_get('islandora_badges_doi_xpath', '/mods:mods/mods:identifier[@type="doi"]')
      );
      if ($xpath_results->length == 0) {
        return;
      }
      $doi = $xpath_results->item(0)->nodeValue;
      if (!$doi) {
        return;
      }

      // Embed Scopus.
      // Assemble the Scopus API request URL
      $api_key = variable_get('islandora_badges_scopus_api_key', 'b3a71de2bde04544495881ed9d2f9c5b');
      $scopus_url = "http://api.elsevier.com:80/content/abstract/citation-count?doi=" .
        urlencode($doi) . "&apiKey=" . $api_key . "&httpAccept=text%2Fhtml";
      // Hit the API.
      $response = drupal_http_request($scopus_url);
      $to_render['content'] = $response->data;
      break;

/** Web of Science block */
   case 'islandora_badges_wos':
      $object = menu_get_object('islandora_object', 2);
      // Get DOI.
      $doc = new DOMDocument();
      $doc->loadXML($object['MODS']->content);
      $xpath = new DOMXPath($doc);
      $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
      $xpath_results = $xpath->query(
        variable_get('islandora_badges_doi_xpath', '/mods:mods/mods:identifier[@type="doi"]')
      );
      if ($xpath_results->length == 0) {
        return;
      }
      $doi = $xpath_results->item(0)->nodeValue;
      if (!$doi) {
        return;
      }
 
    // Embed Web of Science.

    // Get the WoS AMR username and password from the admin config.
      $wos_username = variable_get('islandora_badges_wos_username');
      $wos_password = variable_get('islandora_badges_wos_password');
    
    // Looks like a Hong Kong IR uses JS to generate results in an image: http://repository.ust.hk/ir/themes/hkust/js/hkust_wos_api.js
    
    // Set API endpoint URL
    $url = "https://ws.isiknowledge.com/cps/xrpc";


//Store your XML Request in a variable - not ideal but I don't know how to send an XML file by POST (ha ha)
      $input_xml = '<?xml version="1.0" encoding="UTF-8" ?>
      <request xmlns="http://www.isinet.com/xrpc42" src="app.id=API Demo">
      <fn name="LinksAMR.retrieve">
      <list>
      <!-- WHO IS REQUESTING -->
      <map>   
          <val name="username">' . $wos_username . '</val>       
          <val name="password">' . $wos_password . '</val>            
        </map>
        <!-- WHAT IS REQUESTED -->
        <map>
          <list name="WOS">
            <val>timesCited</val>
          </list>
        </map>
        <!-- LOOKUP DATA -->
        <map>  
          <map name="cite_1">
            <val name="doi">' . $doi . '</val>
          </map>
        </map>
      </list>
    </fn>
  </request>';
      
/* The following was cut from the <list> tag above for testing only:
            <val>ut</val>
            <val>doi</val>
            <val>pmid</val>
            <val>sourceURL</val>
            <val>citingArticlesURL</val>
            <val>relatedRecordsURL</val>
*/      
      
$result = drupal_http_request($url, array(
  'headers' => array('Content-Type' => 'text/xml'),
  'data' => $input_xml,
  'method' => 'POST',
  'timeout' => 10
));

// If there is no error return data
if (empty($result ->error)) {
    $to_render['content'] = $result ->data;
}
      
  }
  return $to_render;
}
