<?php
/**
 * @file
 * Main hooks for Islandora Altmentrics.
 */

/**
 * Implements hook_menu().
 */
function islandora_altmetrics_menu() {
  return array(
    'admin/islandora/tools/altmetrics' => array(
      'title' => 'Islandora Altmetrics Configuration',
      'description' => 'Configure Altmetrics integration.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_altmetrics_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_altmetrics_block_info() {
  return array(
    'islandora_altmetrics_altmetrics' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_NO_CACHE,
      'info' => t('Islandora Altmetrics'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_altmetrics_block_view($delta) {
  $to_render = array();

  switch ($delta) {
    case 'islandora_altmetrics_altmetrics':
      $object = menu_get_object('islandora_object', 2);
      // Limit to citations with MODS DS.
      // if (!in_array('ir:citationCModel', $object->models) || !isset($object['MODS'])) {
        // return;
      // }
      // Get DOI.
      $doc = new DOMDocument();
      $doc->loadXML($object['MODS']->content);
      $xpath = new DOMXPath($doc);
      $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
      $xpath_results = $xpath->query(
        variable_get('islandora_altmetrics_doi_xpath', '/mods:mods/mods:identifier[@type="doi"]')
      );
      if ($xpath_results->length == 0) {
        return;
      }
      $doi = $xpath_results->item(0)->nodeValue;
      if (!$doi) {
        return;
      }

      // Embed Altmetrics.
      // $to_render['content']['altmetrics'] = array(
      // Assemble the Scopus API request URL
      $api_key = variable_get('islandora_altmetrics_scopu_api_key', 'b3a71de2bde04544495881ed9d2f9c5b');
      $scopus_url = "http://api.elsevier.com:80/content/abstract/citation-count?doi=" .
        urlencode($doi) . "&apiKey=" . $api_key . "&httpAccept=text%2Fhtml";
      // Hit the API.
      $response = drupal_http_request($scopus_url);
      $to_render['content'] = $response->data;
      break;
  }
  return $to_render;
}
